MyOwn/BasicApp/urls.py
from django.urls import path
from . import views


app_name = 'BasicApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('special/', views.special, name='special'),
]

MyOwn/MyOwn/urls.py
from django.contrib import admin
from django.urls import path, include
from BasicApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BasicApp.urls')),
]

MyOwn/BasicApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(blank=True, upload_to='profile_pics')

    def __str__(self):
        return self.user.username

MyOwn/BasicApp/forms.py
from django import forms
from .models import User, UserProfileInfo


class UserForm(forms.ModelForm):
    # password1 = forms.CharField(max_length=256, widget=forms.PasswordInput(
    #     attrs={'class': 'form-control', 'placeholder': 'Enter Password'}), label='Password')
    password2 = forms.CharField(max_length=256, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Password Again'}), label='Re-enter Password')

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Password'})
        }

    def clean(self):
        all_cleaned_data = super().clean()
        pass1 = all_cleaned_data['password']
        pass2 = all_cleaned_data['password2']

        if pass1 != pass2:
            raise forms.ValidationError('Passwords did not match')
        return self.cleaned_data


def url_check(value):
    if value[:8] != 'https://' and value[:7] != 'http://':
        raise forms.ValidationError(
            'Invalid URL. Include "https://" or "http://"')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ['portfolio_site', 'profile_pic']
        validators = [url_check]
        widgets = {
            'portfolio_site': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Portfolio Site'}),
            'profile_pic': forms.FileInput(attrs={'class': 'form-control'})
        }
        labels = {
            'portfolio_site': 'Port-Folio Site',
            'profile_pic': 'Profile Photo',
        }

MyOwn/BasicApp/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm

# imports for login and logout
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.


def index(request):
    return render(request, 'BasicApp/index.html')


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileInfoForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'BasicApp/register.html', {'user': user_form, 'profile': profile_form, 'is_registered': registered})


@login_required
def special(request):
    return HttpResponse('You are logged in, Nice!')


@login_required
def user_logout(request):
    logout(request)
    return render(request, 'BasicApp/index.html')


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user != None:
            if user.is_active:
                login(request, user)
                # return redirect('special/')
                return HttpResponseRedirect(reverse('BasicApp:special'))
            else:
                return HttpResponse("User is NOT ACTIVE!")
        else:
            print('Someone tried to login and failed!')
            print('Username: {} \n Password: {}'.format(username, password))
            return HttpResponse('Invalid login details or User does not exist')
    else:
        return render(request, 'BasicApp/login.html',{})

MyOwn/templates/BasicApp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" />
    <title> {% block title_block%}
        <!--Title goes here-->{%endblock title_block%} </title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'BasicApp:index' %}">DJANGO</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin<span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'BasicApp:register' %}">Register</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'BasicApp:user_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'BasicApp:user_login' %}">Login</a>
                    </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        <!-- body of html goes here -->
        {% endblock body_block %}
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>

</html>

MyOwn/templates/BasicApp/index.html
{% extends "BasicApp/base.html" %}
{% block title_block %}
Home Page!
{% endblock title_block %}

{% block body_block %}
<div class="jumbotron">
    <h1>Welcome to the Home Page!</h1>
</div>
{% endblock body_block %}

MyOwn/templates/BasicApp/login.html
{% extends "BasicApp/base.html" %}
{% block title_block %}
Login Page!
{% endblock title_block %}

{% block body_block %}
<div class="jumbotron">
    <h1>Welcome to the Login Page!</h1>
    <hr class="my-4">
    <h2>Login here</h2>
    <hr class="my-4">
    <style>
        .form-group {
            width: 35%;
            text-align: center;
            text-decoration: solid;
            align-items: center;
            margin: auto;
        }

        #arbi {
            width: 25%;
        }
    </style>
    <form method="POST" action="{% url 'BasicApp:user_login' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username: </label>
            <input type="text" id="username" class="form-control" name="username" placeholder="Enter your username">
        </div>
        <div class="form-group">
            <label for="password">Password: </label>
            <input type="password" id="password" class="form-control" name="password" placeholder="Enter password">
        </div>
        <br>
        <div class="form-group" id="arbi">
            <input type="submit" class="form-control btn btn-primary" value="Login">
        </div>
    </form>
</div>
{% endblock body_block %}

MyOwn/templates/BasicApp/register.html
{% extends "BasicApp/base.html" %}
{% block title_block %}

{% if is_registered %}
Registration Done!
{% else %}
Registration Page!
{% endif %}

{% endblock title_block %}

{% block body_block %}
<div class="jumbotron">

    {% if is_registered %}
    <h1>Thank you for Registering!</h1>
    {% else %}
    <h1>Welcome to the Registration Page!</h1>
    <hr class="my-4">
    <h2>Register Here</h2>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{user.as_p}}
        {{profile.as_p}}
        <div class="form-group">
            <input type="submit" class="form-control btn btn-primary" value="Register">
        </div>
    </form>
    {%endif%}
</div>
{% endblock body_block %}